import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import FavoriteContextProvider from "@/context/FavoriteContext/FavoriteContext";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Photos Gallery',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <FavoriteContextProvider>
          {children}
        </FavoriteContextProvider>
      </body>
    </html>
  )
}
